name: Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test project
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Cache maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Set up Java 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
      - name: Test
        uses: mvn clean test
